config/routes.rb
Rails.application.routes.draw do
  root 'sessions#wellcome'
  resources :users, only: %i[new create index show] do
    post 'follow', to: 'users#follow'
    post 'unfollow', to: 'users#unfollow'
  end
  get 'unauthorized', to: 'sessions#unauthorized'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'wellcome', to: 'sessions#wellcome'
  delete 'logout', to: 'sessions#destroy'
  resources :articles
  resources :categories do
    resources :articles do
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  belongs_to :user
  has_many :comments, dependent: :destroy
  belongs_to :category
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  belongs_to :user
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived]

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :followed, foreign_key: 'followed_id', class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  # My articles and comments
  has_many :comments, dependent: :destroy
  has_many :articles, dependent: :destroy

  # Users who follow me
  has_many :rel_followers, foreign_key: :followed_id, class_name: :Follow
  has_many :followers, through: :rel_followers, source: :follower

  # Users I follow
  has_many :rel_followeds, foreign_key: :follower_id, class_name: :Follow
  has_many :followeds, through: :rel_followeds, source: :followed

  def at_name
    '@' + username
  end

  def equal?(other)
    return false if other.blank?

    id == other.id
  end

  def can_see?(other)
    other.id == id or followeds.include?(other)
  end

  def owns_article?(article)
    article.user_id == id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?
  helper_method :cached_categories

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !session[:user_id].nil? && !current_user.nil?
  end

  def authorized
    redirect_to unauthorized_url unless logged_in?
  end

  def cached_categories
    @categories = Category.all.map(&:name) unless defined? @categories
    @categories
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    render 'forbiden' unless current_user.can_see?(@article.user)
  end

  def new
    @article = Article.new
    @categories = Category.all
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :status, :image_url, :category_id, :user_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to root_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: %i[new create wellcome auth_errors unauthorized]
  helper_method :auth_errors
  layout 'external'

  def new; end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to articles_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to wellcome_path
  end

  def auth_errors
    @auth_errors ||= []
  end

  def unauthorized
    @auth_errors = ['You must log-in to see this page']
    render 'wellcome'
  end

  def wellcome; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: %i[new create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @graph_image = UsersHelper.create_user_graph @user
  end

  def new
    @user = User.new
    render layout: 'external'
  end

  def create
    @user = User.create(params.require(:user).permit(:username, :password))
    session[:user_id] = @user.id
    redirect_to articles_path
  end

  def follow
    follower = User.find(params[:follower_user_id])
    followed = User.find(params[:followed_user_id])

    unless followed.blank? || follower.blank?
      followed.followers << follower
      redirect_to request.referrer
    end

    return if followed.blank? || follower.blank?

    followed.followers << follower
    redirect_to request.referrer
  end

  def unfollow
    follower = User.find(params[:follower_user_id])
    followed = User.find(params[:followed_user_id])

    unless followed.blank? || follower.blank?
      followed.followers.delete(follower)
      redirect_to request.referrer
    end

    return if followed.blank? || follower.blank?

    followed.followers.delete(follower)
    redirect_to request.referrer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(text)
    MarkdownConstants::MD_TO_HTML.render(text).html_safe
  end

  def markdown_to_plain(code)
    MarkdownConstants::MD_TO_PLAIN.render(code)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
require 'ruby-graphviz'
require 'fileutils'
require 'tempfile'

module UsersHelper
  IMAGES_PATH = 'app/assets/images/'.freeze

  def self.internal_user_graph_path
    Rails.root.join IMAGES_PATH
  end

  def self.create_user_graph(user)
    g = GraphViz.new(:G, type: :digraph)
    user_node = g.add_nodes(user.username.to_s)
    user_node.set { |_n| _n.color = '#1976D2' }
    user.followers.each do |follower|
      follower_node = g.add_nodes(follower.username.to_s)
      g.add_edges(follower_node, user_node)
    end
    user.followeds.each do |followed|
      followed_node = g.add_nodes(followed.username.to_s)
      g.add_edges(user_node, followed_node)
    end
    file = Tempfile.new(['userimage', '.svg'])
    g.output(svg: file.path)
    file.read.html_safe
  end
end

app/views/articles/_article.html.erb
<div class="col">
  <div class="card flex-md-row mb-4 box-shadow h-md-250">
    <div class="card-body d-flex flex-column align-items-start">
      <strong class="d-inline-block mb-2 text-primary"><%= article.category.name %></strong>
      <h3 class="mb-0">
        <%= article.title %>
      </h3>
      <div class="mb-1 text-muted">updated <%= time_ago_in_words(article.updated_at)%> ago</div>
      <p class="card-text mb-auto">
      <%= markdown_to_plain(article.body[0,180])...%> 
      <%= link_to "Continue reading", article %>
      </p>
    </div>
    <% unless article.image_url.blank? %>
      <img class="card-img-right flex-auto d-none d-md-block" alt="Thumbnail" style="width: 200px; height: 250px;" src=<%= article.image_url %> data-holder-rendered="true">
    <% end %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <% @article.errors.full_messages.each do |message| %>
    <p class="danger"><%= message %></p>
  <%end%>
  <div class="input-group mt-3">
    <%= form.label :title, class:"input-group-text" %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="input-group mt-3">
    <%= form.label :body, class: "input-group-text" %><br>
    <%= form.text_area :body, class: "big form-control" %><br>
  </div>
  <div class="input-group mt-3">
    <%= form.label :image_url, class: "input-group-text" %><br>
    <%= form.text_field :image_url, class: "form-control" %><br>
  </div>
  <div class="col d-flex justify-content-center input-group mt-3">
    <%= form.label "Visibility", class: "input-group-text mr-2" %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public', class: "form-control" %>
  </div>
  <div class="col d-flex justify-content-center input-group mt-3">
    <%= form.label "Category", class: "input-group-text mr-2" %><br>
    <%= form.collection_select(:category_id, Category.all, :id, :name) %>
  </div>
  <div class="col d-flex justify-content-center mb-4 mt-3">
    <%= form.submit "Upload", :class => 'btn btn-primary rounded' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render "form", article: @article %>

app/views/articles/forbiden.html.erb
<p class="alert alert-danger mt-3">
  You can't see this article because you aren't following the author
  (<%= link_to @article.user.at_name, @article.user %>)
</p>

app/views/articles/index.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">Articles</h1>
    <p class="lead my-3">Our blog has <%= Article.public_count %> articles and counting!</p>
    <p class="lead mb-0"><%= link_to "New Article", new_article_path, class: "text-white font-weight-bold" %></p>
  </div>
</div>

<div class="row mb-2">
  <%= render @articles%>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">New Article</h1>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<% content_for :articles_css do %>
  <%= stylesheet_link_tag "github.css" %>
<% end %>

<div class="blog-post">
  <h2 class="blog-post-title"><%= @article.title %></h2>
  <strong>By <%= link_to @article.user.at_name, @article.user %></strong>
  <% unless @article.image_url.blank? %>
    <p><img class="m-3 img-responsive" style="max-width: 80vw;" src=<%= @article.image_url %> alt=""></p>
  <% end %>
  <%= markdown_to_html(@article.body) %>

  <nav class="blog-pagination mb-4">
    <% if current_user.owns_article? @article %>
      <%= link_to "Edit post", edit_article_path(@article), class: "btn btn-outline-secondary rounded" %>
      <%= link_to "Delete post", article_path(@article),
        method: :delete,
        data: { confirm: "Are you sure?" }, class: "btn btn-outline-secondary rounded" %>
    <% end %>
    <div class="btn btn-outline-secondary rounded" onclick="getElementById('add_comment').classList.remove('hidden')">Leave a comment</div>
  </nav>
  <% unless @article.comments.empty? %>
    <h2 class="mt-5">Comments</h2>
    <div class="mt-4">
      <div class="">
        <%= render @article.comments %>
      </div>
    </div>
  <% end %>
  <div class="hidden" id="add_comment">
    <%= render 'comments/form' %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
  <% @category.errors.full_messages.each do |message| %>
    <p class="danger"><%= message %></p>
  <%end%>
  <div class="input-group mt-3">
    <%= form.label :name, class:"input-group-text" %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="input-group mt-3">
    <%= form.label :description, class: "input-group-text" %><br>
    <%= form.text_area :description, class: "big form-control" %><br>
  </div>
  <div class="col d-flex justify-content-center mb-4 mt-3">
    <%= form.submit "Upload", :class => 'btn btn-primary rounded' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render "form", category: @category %>

app/views/categories/index.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">Categories</h1>
    <p class="lead my-3">Our blog has <%= Category.all.length %> categories and counting!</p> 
  </div>
</div>
<div class="row mb-2">
  <ul>
    <% @categories.each do |category| %>
      <li>
        <%= link_to category.name, category %>
        (<%=category.articles.length%> articles) <%= category.description %>
      </li>
    <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= @category.name %></h2>
  <p><%= @category.description %></p>
  <nav class="blog-pagination mb-4">
    <%= link_to "Edit category", edit_category_path(@category), class: "btn btn-outline-secondary rounded" %>
    <%= link_to "Delete category", category_path(@category),
      method: :delete,
      data: { confirm: "Are you sure?" }, class: "btn btn-outline-secondary rounded" %>
  </nav>
  <%= render @category.articles unless @category.articles.empty? %>
</div>

app/views/comments/_comment.html.erb
<% if current_user.can_see?(comment.user) %>
  <div class="card mb-4">
    <div class="card-header">
      <span class="font-weight-bold"><%= link_to comment.user.at_name, comment.user %> </span> on
      <span><%=  comment.created_at.strftime("%B %d of %Y") %></span>
      <%if current_user == comment.user %>
        <%= link_to 'Delete', [comment.article.category, comment.article, comment],
          method: :delete,
          data: { confirm: "Are you sure?" }, class: "float-right" %>
      <%end%>
    </div>
    <div class="card-body">
      <blockquote class="blockquote">
        <p><%= simple_format(comment.body) %></p>
        <footer>  </footer>
      </blockquote>
    </div>
  </div>
<%else%>
  <p class="alert alert-light mt-3">
  This comment is hidden because you aren't following it's author (<%= link_to comment.user.at_name, comment.user %>)
  </p>
<%end%>

app/views/comments/_form.html.erb
<div class="col-md-6 mx-auto">
  <h2 class="text-center">Add a comment</h2>
  <%= form_with model: [ @article.category, @article, @article.comments.build ] do |form| %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <div class="input-group mb-2"> 
      <div class="input-group-prepend">
        <span class="input-group-text">Comment</span>
      </div>
      <%= form.text_area :body, class: "form-control" %>
      <%= form.select :status, ['public', 'private', 'archived'], selected: 'public', class: "dropdown" %>      
    </div>
    <div class="row mb-4">
      <div class="col d-flex justify-content-center">
        <%= form.submit 'Comment', :class => 'btn btn-primary rounded' %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :articles_css %>
  </head>
  <body>
    <div class="container">
      <header class="blog-header py-3">
        <div class="nav-scroller py-1 mb-2">
          <nav class="nav d-flex justify-content-between">
            <a class="btn" href="<%= articles_path %>">All articles</a>
            <a class="btn" href="<%= categories_path %>">All categories</a>
            <% Category.all[0,8].each do |category| %>
              <%= link_to category.name, category, class: "btn text-muted" %>
            <% end %>
            <div class="dropdown">
              <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username.capitalize %>
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'Profile', current_user, class: "dropdown-item" %>
                <%= link_to 'All users', users_path, class: "dropdown-item" %>
                <%= link_to 'Logout', logout_url, method: "delete", class: "dropdown-item" %>
              </div>
            </div>
          </nav>
        </div>
      </header>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/external.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wellcome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="text-center">
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <div class="row d-flex justify-content-center mt-5">
        <div class="col-6">     
          <header class="masthead mb-auto">
            <div class="inner">
              <h1 class="masthead-brand mb-5">Rails News Blog</h1>
              <p class="lead mb-5">
              <% unless cached_categories.nil? || cached_categories.empty? %>
                We have news about
                <% cached_categories.sample(15).each do |category| %>
                  <span class="badge bg-dark bg-secondary text-light"><%= category %></span>
                <% end %>
                and more...
              <% end %>
              </p>
            </div>
          </header>
          <main role="main" class="inner cover"><%= yield %></main>
        </div>    
      </div>
    </div>
  </body>
</html>

app/views/users/_info_card.html.erb
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
              <%= title %>
            </div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">
              <%= value %>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-calendar fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/_list_view.html.erb
<div class="col-md mt-3">
  <ul class="list-group">
    <h4><%= title %>:</h4>
    <% list.each do |item| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to item.send(attribute), item %>
        <span style="font-size: medium;" class="badge badge-primary badge-pill">😎</span>
      </li>
    <%end%>
  </ul>
</div>

app/views/users/_user.html.erb
<div class="col-4 mb-3" >
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= link_to user.at_name, user %></h5>
      <div style="display: inline-flex;">
        <% if current_user.equal?(user) %>
        <% elsif user.followers.include? current_user %>
          <%= form_tag user_unfollow_path(user)  do %>
            <%= hidden_field_tag 'followed_user_id', user.id %>
            <%= hidden_field_tag 'follower_user_id', current_user.id %>
            <%= submit_tag "Unfollow", class: "btn btn-outline-secondary rounded" %>
          <%end%>    
        <% else %>
          <%= form_tag user_follow_path(user) do %>
            <%= hidden_field_tag 'followed_user_id', user.id %>
            <%= hidden_field_tag 'follower_user_id', current_user.id %>
            <%= submit_tag "Follow", class: "btn btn-outline-secondary rounded" %>
          <%end%>
        <%end%> 
        <%= link_to "See profile", user, class: "btn btn-outline-primary rounded ml-2" %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">Users</h1>
    <p class="lead my-3">Our blog has <%= @users.length %> users and counting!</p>
  </div>
</div>
<div class="row mb-2">
  <%= render @users %>
</div>

app/views/users/new.html.erb
<h2 class="text-center mb-5">Create account</h2>
<div class="form-signin text-center">
  <%= form_for @user do |f|%>
    <% @user.errors.full_messages.each do |message| %>
      <p class="alert alert-danger mt-3"><%= message %></p>
    <%end%>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <div class="input-group-text">Username</div>
      </div>
      <%= f.text_field :username, class: 'form-control' %><br>
    </div>
    <div class="input-group mb-4">
      <div class="input-group-prepend">
        <div class="input-group-text">Password</div>
      </div>
      <%= f.password_field :password, class: 'form-control' %><br>
    </div>
    <%= f.submit "Create", :class => 'btn btn-lg btn-primary btn-block' %>
  <%end%>
</div>

app/views/users/show.html.erb
<h1><%= @user.username.capitalize %>'s profile</h1>
<% unless current_user.equal?(@user) %>
  <nav class="blog-pagination mt-3">
    <% if @user.followers.include? current_user %>
      <%= form_tag user_unfollow_path(@user) do %>
        <%= hidden_field_tag 'followed_user_id', @user.id %>
        <%= hidden_field_tag 'follower_user_id', current_user.id %>
        <%= submit_tag "Unfollow", class: "btn btn-outline-secondary rounded" %>
      <%end%>    
    <% else %>
      <%= form_tag user_follow_path(@user) do %>
        <%= hidden_field_tag 'followed_user_id', @user.id %>
        <%= hidden_field_tag 'follower_user_id', current_user.id %>
        <%= submit_tag "Follow", class: "btn btn-outline-secondary rounded" %>
      <%end%>
    <%end%>
  </nav>
<% end %>
<br>

<div class="row mt-2">
  <%= render 'info_card', title: 'Followers', value: @user.followers.length %>
  <%= render 'info_card', title: 'Following', value: @user.followeds.length %>
  <%= render 'info_card', title: 'Posts', value: @user.articles.length %>
  <%= render 'info_card', title: 'Comments', value: @user.comments.length %>
</div>

<div class="row mb-2 shadow">
  <div class="col-md mt-3">
    <ul class="list-group">
      <h4>Social Network graph</h4>
      <div class="mx-auto" style="max-width: 100%;">
        <%= @graph_image %>
      </div>
    </ul>
  </div>
</div>

<div class="row mb-2">
  <% unless @user.followers.empty? %>
    <%= render 'list_view', list: @user.followers, title: 'Followers', attribute: :at_name %>
  <%end%>

  <% unless @user.followeds.empty? %>
    <%= render 'list_view', list: @user.followeds, title: 'Following', attribute: :at_name %>
  <%end%>
</div>

<% unless @user.articles.empty? %>
  <div class="row mb-2">
    <%= render 'list_view', list: @user.articles, title: 'Lattest posts', attribute: :title %>
  </div>
<%end%>